### ISSUE TITLE
gpt-ads-module not working!

### ISSUE THREAD

**Issue by eslamoo** [ax2inc/nuxt-modules#32]
Firstly i would like to thank you for this awesome work, but i wonder about how to use it!

Am trying to implement gpt-ads in my nuxt app but no output, no console errors literally nothing just empty div.

maybe i didn't understand the documentation so it would be a great thing if you provide to us a working example with all possible options.

for example am trying to implement this https://dfpgpt.appspot.com/g/_4$HfM6WF in my project, so whats the best way to make it work

Thanks in advance

**Comment by thor-n** [comment]
Hi, did you get it to work?
